### ISSUE TITLE
Code with _ and # can't be rendered

### ISSUE THREAD

**Issue by TanguyBarthelemy** [nschloe/github-math-bugs#1]
I try to render the equations:

- The first one with just an underscore _:

```
$\_$
```
$\_$

- The second also with an underscore _:

```
$$ mean\_Day_{i, j} = \sum_{years} Day_{i, j, k} $$
```
$$ mean\_Day_{i, j} = \sum_{years} Day_{i, j, k} $$

- The third with a sharp  #:

```
$$ mean = \#group_i + \#group_j $$
```
$$ mean = \#group_i + \#group_j $$

I saw that you covered the subject well. Maybe I missed something or these are bugs in the formula display under Github.

Thank you for your opinion!

**Comment by nschloe** [comment]
Never use the `$...$` syntax, it's inherintly broken. Best use
```markdown
$`...`$
```
Haven't tried, but I'm guessing this will fix all your issues.

**Comment by TanguyBarthelemy** [comment]
Thanks! it solved my problem for inline code.

For example, the variable $`var\_mean`$  is accepted now and this one $`\#groupe_{13}`$ also! 

but for code in double $$, it doesn't I have the impression:

$$ mean`\_`day_{i, j} = `\#`group_i + `\#`group_j $$
$$mean`\_`day_{i, j} = `\#`group_i + `\#`group_j$$
$$ `mean\_day_{i, j} = \#group_i + \#group_j` $$
$$`mean\_day_{i, j} = \#group_i + \#group_j`$$

I will more test it!
